### ISSUE TITLE
is there a way to have the yaml files included in the compiled binary?

### ISSUE THREAD

**Issue by masukomi** [whity/crystal-i18n#3]
It looks like if i want to ship an app that uses this i also have to ship a folder of yaml translation files. Obviously I'd rather just ship people a binary. Is there a way to make this happen?

**Comment by whity** [comment]
I'm sorry for the late reply, maybe you could try the package "https://github.com/schovi/baked_file_system".
Other option is to load the translations from a 'Hash', `I18n.from_hash({'pt' => {'hello' => 'olá'})`

**Comment by masukomi** [comment]
thanks for the pointer. I think we can close this as "not as part of this lib".
